version: '3'
services:
  web:
    build: .
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
    ports:
        - "5000:5000"
    volumes:
        - .:/code
